/*
 * pwix:accounts/src/common/js/constants.js
 */

// connection status
AC_LOGGED = 'AC_LOGGED';
AC_UNLOGGED = 'AC_UNLOGGED';

// action of the button
AC_ACT_HIDDEN = 'AC_ACT_HIDDEN';
AC_ACT_NONE = 'AC_ACT_NONE';
AC_ACT_DROPDOWN = 'AC_ACT_DROPDOWN';
AC_ACT_BUBBLE = 'AC_ACT_BUBBLE';

// username / email address input rule
AC_FIELD_NONE = 'AC_FIELD_NONE';
AC_FIELD_OPTIONAL = 'AC_FIELD_OPTIONAL';
AC_FIELD_MANDATORY = 'AC_FIELD_MANDATORY';

// known panels
AC_PANEL_NONE = 'AC_PANEL_NONE';
AC_PANEL_CHANGEPWD = 'AC_PANEL_CHANGEPWD';
AC_PANEL_RESETASK = 'AC_PANEL_RESETASK';
AC_PANEL_RESETPWD = 'AC_PANEL_RESETPWD';
AC_PANEL_SIGNIN = 'AC_PANEL_SIGNIN';
AC_PANEL_SIGNOUT = 'AC_PANEL_SIGNOUT';
AC_PANEL_SIGNUP = 'AC_PANEL_SIGNUP';
AC_PANEL_VERIFYASK = 'AC_PANEL_VERIFYASK';

// password estimated strength
AC_PWD_VERYWEAK = 'AC_PWD_VERYWEAK';
AC_PWD_WEAK = 'AC_PWD_WEAK';
AC_PWD_MEDIUM = 'AC_PWD_MEDIUM';
AC_PWD_STRONG = 'AC_PWD_STRONG';
AC_PWD_VERYSTRONG = 'AC_PWD_VERYSTRONG';

// rendering mode
AC_RENDER_MODAL = 'AC_RENDER_MODAL';
AC_RENDER_DIV = 'AC_RENDER_DIV';

// frontend toolbox
AC_UI_BOOTSTRAP = 'AC_UI_BOOTSTRAP';
AC_UI_JQUERY = 'AC_UI_JQUERY';

// non exported internal constant as i18n namespace

AC_I18N = 'pwix:accounts'
